# coding: utf-8

"""
    Ed-Fi Operational Data Store API

    The Ed-Fi ODS / API enables applications to read and write education data stored in an Ed-Fi ODS through a secure REST interface.  ***  > *Note: Consumers of ODS / API information should sanitize all data for display and storage. The ODS / API provides reasonable safeguards against cross-site scripting attacks and other malicious content, but the platform does not and cannot guarantee that the data it contains is free of all potentially harmful content.*  ***   # noqa: E501

    OpenAPI spec version: 3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class EdFiStudentAssessmentStudentObjectiveAssessment(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'objective_assessment_reference': 'EdFiObjectiveAssessmentReference',
        'performance_levels': 'list[EdFiStudentAssessmentStudentObjectiveAssessmentPerformanceLevel]',
        'score_results': 'list[EdFiStudentAssessmentStudentObjectiveAssessmentScoreResult]'
    }

    attribute_map = {
        'objective_assessment_reference': 'objectiveAssessmentReference',
        'performance_levels': 'performanceLevels',
        'score_results': 'scoreResults'
    }

    def __init__(self, objective_assessment_reference=None, performance_levels=None, score_results=None, _configuration=None):  # noqa: E501
        """EdFiStudentAssessmentStudentObjectiveAssessment - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._objective_assessment_reference = None
        self._performance_levels = None
        self._score_results = None
        self.discriminator = None

        self.objective_assessment_reference = objective_assessment_reference
        if performance_levels is not None:
            self.performance_levels = performance_levels
        self.score_results = score_results

    @property
    def objective_assessment_reference(self):
        """Gets the objective_assessment_reference of this EdFiStudentAssessmentStudentObjectiveAssessment.  # noqa: E501


        :return: The objective_assessment_reference of this EdFiStudentAssessmentStudentObjectiveAssessment.  # noqa: E501
        :rtype: EdFiObjectiveAssessmentReference
        """
        return self._objective_assessment_reference

    @objective_assessment_reference.setter
    def objective_assessment_reference(self, objective_assessment_reference):
        """Sets the objective_assessment_reference of this EdFiStudentAssessmentStudentObjectiveAssessment.


        :param objective_assessment_reference: The objective_assessment_reference of this EdFiStudentAssessmentStudentObjectiveAssessment.  # noqa: E501
        :type: EdFiObjectiveAssessmentReference
        """
        if self._configuration.client_side_validation and objective_assessment_reference is None:
            raise ValueError("Invalid value for `objective_assessment_reference`, must not be `None`")  # noqa: E501

        self._objective_assessment_reference = objective_assessment_reference

    @property
    def performance_levels(self):
        """Gets the performance_levels of this EdFiStudentAssessmentStudentObjectiveAssessment.  # noqa: E501

        An unordered collection of studentAssessmentStudentObjectiveAssessmentPerformanceLevels. The PerformanceLevel(s) achieved for the ObjectiveAssessment.  # noqa: E501

        :return: The performance_levels of this EdFiStudentAssessmentStudentObjectiveAssessment.  # noqa: E501
        :rtype: list[EdFiStudentAssessmentStudentObjectiveAssessmentPerformanceLevel]
        """
        return self._performance_levels

    @performance_levels.setter
    def performance_levels(self, performance_levels):
        """Sets the performance_levels of this EdFiStudentAssessmentStudentObjectiveAssessment.

        An unordered collection of studentAssessmentStudentObjectiveAssessmentPerformanceLevels. The PerformanceLevel(s) achieved for the ObjectiveAssessment.  # noqa: E501

        :param performance_levels: The performance_levels of this EdFiStudentAssessmentStudentObjectiveAssessment.  # noqa: E501
        :type: list[EdFiStudentAssessmentStudentObjectiveAssessmentPerformanceLevel]
        """

        self._performance_levels = performance_levels

    @property
    def score_results(self):
        """Gets the score_results of this EdFiStudentAssessmentStudentObjectiveAssessment.  # noqa: E501

        An unordered collection of studentAssessmentStudentObjectiveAssessmentScoreResults. A meaningful score or statistical expression of the performance of an individual. The results can be expressed as a number, percentile, range, level, etc.  # noqa: E501

        :return: The score_results of this EdFiStudentAssessmentStudentObjectiveAssessment.  # noqa: E501
        :rtype: list[EdFiStudentAssessmentStudentObjectiveAssessmentScoreResult]
        """
        return self._score_results

    @score_results.setter
    def score_results(self, score_results):
        """Sets the score_results of this EdFiStudentAssessmentStudentObjectiveAssessment.

        An unordered collection of studentAssessmentStudentObjectiveAssessmentScoreResults. A meaningful score or statistical expression of the performance of an individual. The results can be expressed as a number, percentile, range, level, etc.  # noqa: E501

        :param score_results: The score_results of this EdFiStudentAssessmentStudentObjectiveAssessment.  # noqa: E501
        :type: list[EdFiStudentAssessmentStudentObjectiveAssessmentScoreResult]
        """
        if self._configuration.client_side_validation and score_results is None:
            raise ValueError("Invalid value for `score_results`, must not be `None`")  # noqa: E501

        self._score_results = score_results

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(EdFiStudentAssessmentStudentObjectiveAssessment, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EdFiStudentAssessmentStudentObjectiveAssessment):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, EdFiStudentAssessmentStudentObjectiveAssessment):
            return True

        return self.to_dict() != other.to_dict()
