# coding: utf-8

"""
    Ed-Fi Operational Data Store API

    The Ed-Fi ODS / API enables applications to read and write education data stored in an Ed-Fi ODS through a secure REST interface.  ***  > *Note: Consumers of ODS / API information should sanitize all data for display and storage. The ODS / API provides reasonable safeguards against cross-site scripting attacks and other malicious content, but the platform does not and cannot guarantee that the data it contains is free of all potentially harmful content.*  ***   # noqa: E501

    OpenAPI spec version: 3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class EdFiStudentDisciplineIncidentNonOffenderAssociationDisciplineIncidentParticipationCode(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'discipline_incident_participation_code_descriptor': 'str'
    }

    attribute_map = {
        'discipline_incident_participation_code_descriptor': 'disciplineIncidentParticipationCodeDescriptor'
    }

    def __init__(self, discipline_incident_participation_code_descriptor=None, _configuration=None):  # noqa: E501
        """EdFiStudentDisciplineIncidentNonOffenderAssociationDisciplineIncidentParticipationCode - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._discipline_incident_participation_code_descriptor = None
        self.discriminator = None

        self.discipline_incident_participation_code_descriptor = discipline_incident_participation_code_descriptor

    @property
    def discipline_incident_participation_code_descriptor(self):
        """Gets the discipline_incident_participation_code_descriptor of this EdFiStudentDisciplineIncidentNonOffenderAssociationDisciplineIncidentParticipationCode.  # noqa: E501

        The role or type of participation of a student in a discipline incident.  # noqa: E501

        :return: The discipline_incident_participation_code_descriptor of this EdFiStudentDisciplineIncidentNonOffenderAssociationDisciplineIncidentParticipationCode.  # noqa: E501
        :rtype: str
        """
        return self._discipline_incident_participation_code_descriptor

    @discipline_incident_participation_code_descriptor.setter
    def discipline_incident_participation_code_descriptor(self, discipline_incident_participation_code_descriptor):
        """Sets the discipline_incident_participation_code_descriptor of this EdFiStudentDisciplineIncidentNonOffenderAssociationDisciplineIncidentParticipationCode.

        The role or type of participation of a student in a discipline incident.  # noqa: E501

        :param discipline_incident_participation_code_descriptor: The discipline_incident_participation_code_descriptor of this EdFiStudentDisciplineIncidentNonOffenderAssociationDisciplineIncidentParticipationCode.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and discipline_incident_participation_code_descriptor is None:
            raise ValueError("Invalid value for `discipline_incident_participation_code_descriptor`, must not be `None`")  # noqa: E501
        if (self._configuration.client_side_validation and
                discipline_incident_participation_code_descriptor is not None and len(discipline_incident_participation_code_descriptor) > 306):
            raise ValueError("Invalid value for `discipline_incident_participation_code_descriptor`, length must be less than or equal to `306`")  # noqa: E501

        self._discipline_incident_participation_code_descriptor = discipline_incident_participation_code_descriptor

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(EdFiStudentDisciplineIncidentNonOffenderAssociationDisciplineIncidentParticipationCode, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EdFiStudentDisciplineIncidentNonOffenderAssociationDisciplineIncidentParticipationCode):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, EdFiStudentDisciplineIncidentNonOffenderAssociationDisciplineIncidentParticipationCode):
            return True

        return self.to_dict() != other.to_dict()
