# coding: utf-8

"""
    Ed-Fi Operational Data Store API

    The Ed-Fi ODS / API enables applications to read and write education data stored in an Ed-Fi ODS through a secure REST interface.  ***  > *Note: Consumers of ODS / API information should sanitize all data for display and storage. The ODS / API provides reasonable safeguards against cross-site scripting attacks and other malicious content, but the platform does not and cannot guarantee that the data it contains is free of all potentially harmful content.*  ***   # noqa: E501

    OpenAPI spec version: 3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class TpdmTeacherCandidateStaffAssociation(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'staff_reference': 'EdFiStaffReference',
        'teacher_candidate_reference': 'TpdmTeacherCandidateReference',
        'begin_date': 'date',
        'end_date': 'date',
        'etag': 'str'
    }

    attribute_map = {
        'id': 'id',
        'staff_reference': 'staffReference',
        'teacher_candidate_reference': 'teacherCandidateReference',
        'begin_date': 'beginDate',
        'end_date': 'endDate',
        'etag': '_etag'
    }

    def __init__(self, id=None, staff_reference=None, teacher_candidate_reference=None, begin_date=None, end_date=None, etag=None):  # noqa: E501
        """TpdmTeacherCandidateStaffAssociation - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._staff_reference = None
        self._teacher_candidate_reference = None
        self._begin_date = None
        self._end_date = None
        self._etag = None
        self.discriminator = None

        if id is not None:
            self.id = id
        self.staff_reference = staff_reference
        self.teacher_candidate_reference = teacher_candidate_reference
        self.begin_date = begin_date
        if end_date is not None:
            self.end_date = end_date
        if etag is not None:
            self.etag = etag

    @property
    def id(self):
        """Gets the id of this TpdmTeacherCandidateStaffAssociation.  # noqa: E501

          # noqa: E501

        :return: The id of this TpdmTeacherCandidateStaffAssociation.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this TpdmTeacherCandidateStaffAssociation.

          # noqa: E501

        :param id: The id of this TpdmTeacherCandidateStaffAssociation.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def staff_reference(self):
        """Gets the staff_reference of this TpdmTeacherCandidateStaffAssociation.  # noqa: E501


        :return: The staff_reference of this TpdmTeacherCandidateStaffAssociation.  # noqa: E501
        :rtype: EdFiStaffReference
        """
        return self._staff_reference

    @staff_reference.setter
    def staff_reference(self, staff_reference):
        """Sets the staff_reference of this TpdmTeacherCandidateStaffAssociation.


        :param staff_reference: The staff_reference of this TpdmTeacherCandidateStaffAssociation.  # noqa: E501
        :type: EdFiStaffReference
        """
        if staff_reference is None:
            raise ValueError("Invalid value for `staff_reference`, must not be `None`")  # noqa: E501

        self._staff_reference = staff_reference

    @property
    def teacher_candidate_reference(self):
        """Gets the teacher_candidate_reference of this TpdmTeacherCandidateStaffAssociation.  # noqa: E501


        :return: The teacher_candidate_reference of this TpdmTeacherCandidateStaffAssociation.  # noqa: E501
        :rtype: TpdmTeacherCandidateReference
        """
        return self._teacher_candidate_reference

    @teacher_candidate_reference.setter
    def teacher_candidate_reference(self, teacher_candidate_reference):
        """Sets the teacher_candidate_reference of this TpdmTeacherCandidateStaffAssociation.


        :param teacher_candidate_reference: The teacher_candidate_reference of this TpdmTeacherCandidateStaffAssociation.  # noqa: E501
        :type: TpdmTeacherCandidateReference
        """
        if teacher_candidate_reference is None:
            raise ValueError("Invalid value for `teacher_candidate_reference`, must not be `None`")  # noqa: E501

        self._teacher_candidate_reference = teacher_candidate_reference

    @property
    def begin_date(self):
        """Gets the begin_date of this TpdmTeacherCandidateStaffAssociation.  # noqa: E501

        The month, day, and year on which the teacher candidate is associated to the staff.  # noqa: E501

        :return: The begin_date of this TpdmTeacherCandidateStaffAssociation.  # noqa: E501
        :rtype: date
        """
        return self._begin_date

    @begin_date.setter
    def begin_date(self, begin_date):
        """Sets the begin_date of this TpdmTeacherCandidateStaffAssociation.

        The month, day, and year on which the teacher candidate is associated to the staff.  # noqa: E501

        :param begin_date: The begin_date of this TpdmTeacherCandidateStaffAssociation.  # noqa: E501
        :type: date
        """
        if begin_date is None:
            raise ValueError("Invalid value for `begin_date`, must not be `None`")  # noqa: E501

        self._begin_date = begin_date

    @property
    def end_date(self):
        """Gets the end_date of this TpdmTeacherCandidateStaffAssociation.  # noqa: E501

        The month, day, and year on which the teacher candidate stops association with the staff.  # noqa: E501

        :return: The end_date of this TpdmTeacherCandidateStaffAssociation.  # noqa: E501
        :rtype: date
        """
        return self._end_date

    @end_date.setter
    def end_date(self, end_date):
        """Sets the end_date of this TpdmTeacherCandidateStaffAssociation.

        The month, day, and year on which the teacher candidate stops association with the staff.  # noqa: E501

        :param end_date: The end_date of this TpdmTeacherCandidateStaffAssociation.  # noqa: E501
        :type: date
        """

        self._end_date = end_date

    @property
    def etag(self):
        """Gets the etag of this TpdmTeacherCandidateStaffAssociation.  # noqa: E501

        A unique system-generated value that identifies the version of the resource.  # noqa: E501

        :return: The etag of this TpdmTeacherCandidateStaffAssociation.  # noqa: E501
        :rtype: str
        """
        return self._etag

    @etag.setter
    def etag(self, etag):
        """Sets the etag of this TpdmTeacherCandidateStaffAssociation.

        A unique system-generated value that identifies the version of the resource.  # noqa: E501

        :param etag: The etag of this TpdmTeacherCandidateStaffAssociation.  # noqa: E501
        :type: str
        """

        self._etag = etag

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TpdmTeacherCandidateStaffAssociation, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TpdmTeacherCandidateStaffAssociation):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
